name: Compile Wordls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  paths-ignore:
      - '**.md'
      - '**.gitignore'
      - 'LICENSE'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Compile UserWordl
        run: make

      - name: Swap Compile Files
        run: |
          chmod +x ./scripts/switchCppFiles.sh
          ./scripts/switchCppFiles.sh
        shell: bash

      - name: Compile WordlBot
        run: make
